
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Exclude:
    - vendor/**/*
    - spec/fixtures/**/*
    - .git/**/*
    - bin/**/*
    - config/routes
    - db/**/*
    - node_modules/**/*
    - tmp/**/*
    - log/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false

# Rails:
#   Enabled: true

Metrics/MethodLength:
  Max: 24

Metrics/AbcSize:
  Max: 32

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'

# Rails/InverseOf:
#   Enabled: false

# Rails/HasManyOrHasOneDependent:
#   Enabled: false

# Rails/SkipsModelValidations:
#   Enabled: false

# Rails/DynamicFindBy:
#   Enabled: false

# Rails/HttpPositionalArguments:
#   Enabled: false

# Metrics/BlockLength:
#   Max: 256
#   Exclude:
#     - spec/**/*

# Metrics/ClassLength:
#   Max: 300

# Metrics/ModuleLength:
#   Max: 270

# Metrics/CyclomaticComplexity:
#   Max: 10

# Metrics/PerceivedComplexity:
#   Max: 10

# Style/Documentation:
#   Enabled: false

# Style/GlobalVars:
#   Enabled: false

# Style/FormatString:
#   Enabled: false

# Style/EmptyCaseCondition:
#   Enabled: false

# Style/EmptyMethod:
#   EnforcedStyle: expanded

# Style/DateTime:
#   Enabled: false

# Style/NumericLiteralPrefix:
#   Enabled: false

# Style/NestedParenthesizedCalls:
#   Enabled: false

# Style/ClassAndModuleChildren:
#   Enabled: false

# Style/FormatStringToken:
#   Enabled: false

# Style/NumericPredicate:
#   Enabled: false

# Style/SafeNavigation:
#   Enabled: false

# Layout/AlignHash:
#   Enabled: false

# Layout/ElseAlignment:
#   Enabled: false

# Layout/IndentArray:
#   Enabled: false

# Layout/EndAlignment:
#   EnforcedStyleAlignWith: variable

# Layout/AlignParameters:
#   EnforcedStyle: with_fixed_indentation
#   SupportedStyles:
#     - with_first_parameter
#     - with_fixed_indentation

# Layout/MultilineMethodCallBraceLayout:
#   Enabled: false
#   # EnforcedStyle: new_line
#   # SupportedStyles:
#   #   - symmetrical
#   #   - new_line
#   #   - same_line

# Layout/MultilineArrayBraceLayout:
#   Enabled: false
#   # EnforcedStyle: new_line
#   # SupportedStyles:
#   #   - symmetrical
#   #   - new_line
#   #   - same_line

# Layout/SpaceInLambdaLiteral:
#   EnforcedStyle: require_space

# Layout/MultilineMethodCallIndentation:
#   Enabled: false
#   # EnforcedStyle: aligned
#   # SupportedStyles:
#   #   - aligned
#   #   - indented
#   #   - indented_relative_to_receiver

# Lint/AmbiguousBlockAssociation:
#   Enabled: false
