default: &default
  adapter: postgresql
  user: postgres
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default
  database: trellon_development

test:
  <<: *default
  database: trellon_test

production:
  <<: *default
  database: TrelloN_production
  username: TrelloN
  password: <%= ENV['TRELLON_DATABASE_PASSWORD'] %>
