server:
  http_listen_port: 0
  grpc_listen_port: 0
        
positions:
  filename: /tmp/positions.yaml
        
client:
  url: https://181579:eyJrIjoiZmYwMmU2ZTBjODRmNTg5MWE0ZjU1YmY3ZDAzZTE2MjU4M2RjMTI3ZiIsIm4iOiJUcmVsbG9OIiwiaWQiOjYxNzYwMH0=@logs-prod3.grafana.net/api/prom/push
        
scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log
